name: "Build and Publish Vercel Deployment Extension"

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.3.1
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Set to preview version
        run: |
          jq '. += { "id": "vercel-deployment-extension-preview", "public": false, "galleryFlags": ["Preview"] }' vss-extension.json > temp.json \
          && mv temp.json vss-extension.json \
          && pnpm exec prettier --write vss-extension.json
          echo "Updated vss-extension.json"

      - name: Build and Publish
        run: pnpm -C scripts build-and-publish
        env:
          AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}
